### ISSUE TITLE
Clover-Edition

### ISSUE THREAD

**Issue by Muskelmagier** [OpenCYOAI/OpenCYOAI#1]
It would be nice if Installing the Clover-Edition would be easier or at least better explained.

The Colab v1.22 can't download the model of the Clover edition so I have to manually download the Torrent. But now I have the model_v5_pytorch on my google drive but I don't know where to put it.

I tried to put the model_5v_pytorch into both model subfolders of Aidungeon in my Google Drive (Google Drive\AIDungeon\generator\gpt2\models and Google Drive\AIDungeon\Clover-Edition\models), but the Colab v1.22 says it wants to redownload the model (which doesn't work).

I am using Firefox 71.0 (64-Bit)

**Comment by Muskelmagier** [comment]
i found the problem 

The colab wants for clover the 

pytorch-gpt2-xl-aid2-v5

but if i download the torrent  it is simply named 

model_5v_pytorch

**Comment by OpenCYOAI** [comment]
yeah, 1.22 starts to be quite deprecated... you have 2 solutions to use the pytorch model

1/ use the beta ipynb

2/ rename model_v5_pytorch to pytorch-gpt2-xl-aid2-v5 and drop it in models folder of clover

**Comment by OpenCYOAI** [comment]
didn't saw your post. now clover don't rely on a folder name so the latest beta switched back to the torrent foldername. gonna get rid of foldername method when we'll implement a model selector
